service: my-kindlegen-lambda

frameworkVersion: ">=1.1.0"

custom:
  bucket: my-kindlegen-${self:provider.stage}

provider:
  name: aws
  profile: serverless-cli
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
  runtime: nodejs14.x

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", "${self:custom.bucket}", '/*' ] ]  }

functions:
  convert:
    handler: convert/handler.onUpload
    timeout: 300 # 5mins , default is 6 seconds
    events:
      # the S3 Bucket will be created if not already, SHOULD NOT be defined in 'resources'
      - s3: ${self:custom.bucket}
        event: s3:ObjectCreated:*
        # rules:
        #   - suffix: .epub
    layers:
      # Use the exported AWS Layer from the other CloudFormation stack
      # the name of the CloudFormation is 'my-kindlegen-layer-dev' (for dev stage) and it exports 'KindlegenLayerExport'
      - ${cf:my-kindlegen-layer-${self:provider.stage}.KindlegenLayerExport}

  # client-authorize:
  #   handler: client/handler.authorize
  #   timeout: 300 # 5mins , default is 6 seconds
  #   events:
